
INSERT INTO stories (id, owner_id, creation_time, title, content, completed)
VALUES
(1, 1, '2022-01-01', 'Totally real title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Longum est enim ad omnia respondere, quae a te dicta sunt. Tecum optime, deinde etiam cum mediocri amico. Res enim fortasse verae, certe graves, non ita tractantur, ut debent, sed aliquanto minutius. Minime vero istorum quidem, inquit. Duo Reges: constructio interrete.', FALSE),
(2, 1, '2022-02-02', 'Another real title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quorum sine causa fieri nihil putandum est. Tum ille timide vel potius verecunde: Facio, inquit. Atque haec coniunctio confusioque virtutum tamen a philosophis ratione quadam distinguitur. Duo Reges: constructio interrete. Ut in voluptate sit, qui epuletur, in dolore, qui torqueatur. Immo videri fortasse. Omnia peccata paria dicitis. Cum ageremus, inquit, vitae beatum et eundem supremum diem, scribebamus haec. Est enim effectrix multarum et magnarum voluptatum. Cur fortior sit, si illud, quod tute concedis, asperum et vix ferendum putabit?', FALSE),
(3, 3, '2021-12-24', 'Real book to movie', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. At hoc in eo M. Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Memini me adesse P. Si qua in iis corrigere voluit, deteriora fecit. Duo Reges: constructio interrete. Summae mihi videtur inscitiae. Huius ego nunc auctoritatem sequens idem faciam. Quibus ego vehementer assentior.', TRUE),
(4, 3, '2021-01-01', 'Book covers over here', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Longum est enim ad omnia respondere, quae a te dicta sunt. Tecum optime, deinde etiam cum mediocri amico. Res enim fortasse verae, certe graves, non ita tractantur, ut debent, sed aliquanto minutius. Minime vero istorum quidem, inquit. Duo Reges: constructio interrete.', FALSE),
(5, 4, '2022-03-02', 'One two three four', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quorum sine causa fieri nihil putandum est. Tum ille timide vel potius verecunde: Facio, inquit. Atque haec coniunctio confusioque virtutum tamen a philosophis ratione quadam distinguitur. Duo Reges: constructio interrete. Ut in voluptate sit, qui epuletur, in dolore, qui torqueatur. Immo videri fortasse. Omnia peccata paria dicitis. Cum ageremus, inquit, vitae beatum et eundem supremum diem, scribebamus haec. Est enim effectrix multarum et magnarum voluptatum. Cur fortior sit, si illud, quod tute concedis, asperum et vix ferendum putabit?', FALSE),
(6, 5, '2021-12-14', 'Mug rain glass grass', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. At hoc in eo M. Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Memini me adesse P. Si qua in iis corrigere voluit, deteriora fecit. Duo Reges: constructio interrete. Summae mihi videtur inscitiae. Huius ego nunc auctoritatem sequens idem faciam. Quibus ego vehementer assentior.', TRUE),
(7, 1, '2022-11-01', 'Monitor television', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Longum est enim ad omnia respondere, quae a te dicta sunt. Tecum optime, deinde etiam cum mediocri amico. Res enim fortasse verae, certe graves, non ita tractantur, ut debent, sed aliquanto minutius. Minime vero istorum quidem, inquit. Duo Reges: constructio interrete.', FALSE),
(8, 1, '2022-02-11', 'And another one', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quorum sine causa fieri nihil putandum est. Tum ille timide vel potius verecunde: Facio, inquit. Atque haec coniunctio confusioque virtutum tamen a philosophis ratione quadam distinguitur. Duo Reges: constructio interrete. Ut in voluptate sit, qui epuletur, in dolore, qui torqueatur. Immo videri fortasse. Omnia peccata paria dicitis. Cum ageremus, inquit, vitae beatum et eundem supremum diem, scribebamus haec. Est enim effectrix multarum et magnarum voluptatum. Cur fortior sit, si illud, quod tute concedis, asperum et vix ferendum putabit?', FALSE),
(9, 1, '2021-07-24', 'Check out this book', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. At hoc in eo M. Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Memini me adesse P. Si qua in iis corrigere voluit, deteriora fecit. Duo Reges: constructio interrete. Summae mihi videtur inscitiae. Huius ego nunc auctoritatem sequens idem faciam. Quibus ego vehementer assentior.', TRUE),
(10, 6, '2021-11-01', 'Good bye world', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Longum est enim ad omnia respondere, quae a te dicta sunt. Tecum optime, deinde etiam cum mediocri amico. Res enim fortasse verae, certe graves, non ita tractantur, ut debent, sed aliquanto minutius. Minime vero istorum quidem, inquit. Duo Reges: constructio interrete.', FALSE),
(11, 1, '2022-04-02', 'Hello world', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quorum sine causa fieri nihil putandum est. Tum ille timide vel potius verecunde: Facio, inquit. Atque haec coniunctio confusioque virtutum tamen a philosophis ratione quadam distinguitur. Duo Reges: constructio interrete. Ut in voluptate sit, qui epuletur, in dolore, qui torqueatur. Immo videri fortasse. Omnia peccata paria dicitis. Cum ageremus, inquit, vitae beatum et eundem supremum diem, scribebamus haec. Est enim effectrix multarum et magnarum voluptatum. Cur fortior sit, si illud, quod tute concedis, asperum et vix ferendum putabit?', FALSE),
(12, 2, '2021-06-24', 'Night time lights', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. At hoc in eo M. Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Memini me adesse P. Si qua in iis corrigere voluit, deteriora fecit. Duo Reges: constructio interrete. Summae mihi videtur inscitiae. Huius ego nunc auctoritatem sequens idem faciam. Quibus ego vehementer assentior.', TRUE),
(13, 6, '2022-08-01', 'Windy sky', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Longum est enim ad omnia respondere, quae a te dicta sunt. Tecum optime, deinde etiam cum mediocri amico. Res enim fortasse verae, certe graves, non ita tractantur, ut debent, sed aliquanto minutius. Minime vero istorum quidem, inquit. Duo Reges: constructio interrete.', FALSE),
(14, 2, '2022-04-02', 'Better story', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quorum sine causa fieri nihil putandum est. Tum ille timide vel potius verecunde: Facio, inquit. Atque haec coniunctio confusioque virtutum tamen a philosophis ratione quadam distinguitur. Duo Reges: constructio interrete. Ut in voluptate sit, qui epuletur, in dolore, qui torqueatur. Immo videri fortasse. Omnia peccata paria dicitis. Cum ageremus, inquit, vitae beatum et eundem supremum diem, scribebamus haec. Est enim effectrix multarum et magnarum voluptatum. Cur fortior sit, si illud, quod tute concedis, asperum et vix ferendum putabit?', FALSE),
(15, 2, '2021-02-24', 'New story here', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. At hoc in eo M. Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Memini me adesse P. Si qua in iis corrigere voluit, deteriora fecit. Duo Reges: constructio interrete. Summae mihi videtur inscitiae. Huius ego nunc auctoritatem sequens idem faciam. Quibus ego vehementer assentior.', TRUE);

