INSERT INTO contributions (id, story_id, additions, rating)
VALUES
(1, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. At hoc in eo M. Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Memini me adesse P. Si qua in iis corrigere voluit, deteriora fecit. Duo Reges: constructio interrete. Summae mihi videtur inscitiae. Huius ego nunc auctoritatem sequens idem faciam. Quibus ego vehementer assentior.', -3),
(2, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sint ista Graecorum; Erat enim Polemonis. Pugnant Stoici cum Peripateticis. Laboro autem non sine causa;', 0),
(3, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. Quonam modo? Vitae autem degendae ratio maxime quidem illis placuit quieta. Duo Reges: constructio interrete.', 5), (4, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. At hoc in eo M. Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Memini me adesse P. Si qua in iis corrigere voluit, deteriora fecit. Duo Reges: constructio interrete. Summae mihi videtur inscitiae. Huius ego nunc auctoritatem sequens idem faciam. Quibus ego vehementer assentior.', 8),
(5, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sint ista Graecorum; Erat enim Polemonis. Pugnant Stoici cum Peripateticis. Laboro autem non sine causa;', 2),
(63, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. Quonam modo? Vitae autem degendae ratio maxime quidem illis placuit quieta. Duo Reges: constructio interrete.', 7), (7, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. At hoc in eo M. Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Memini me adesse P. Si qua in iis corrigere voluit, deteriora fecit. Duo Reges: constructio interrete. Summae mihi videtur inscitiae. Huius ego nunc auctoritatem sequens idem faciam. Quibus ego vehementer assentior.', -7),
(8, 10, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sint ista Graecorum; Erat enim Polemonis. Pugnant Stoici cum Peripateticis. Laboro autem non sine causa;', 1),
(9, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. Quonam modo? Vitae autem degendae ratio maxime quidem illis placuit quieta. Duo Reges: constructio interrete.', 5), (10, 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. At hoc in eo M. Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Memini me adesse P. Si qua in iis corrigere voluit, deteriora fecit. Duo Reges: constructio interrete. Summae mihi videtur inscitiae. Huius ego nunc auctoritatem sequens idem faciam. Quibus ego vehementer assentior.', -3),
(11, 9, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sint ista Graecorum; Erat enim Polemonis. Pugnant Stoici cum Peripateticis. Laboro autem non sine causa;', 0),
(12, 8, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. Quonam modo? Vitae autem degendae ratio maxime quidem illis placuit quieta. Duo Reges: constructio interrete.', 5), (13, 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. At hoc in eo M. Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Memini me adesse P. Si qua in iis corrigere voluit, deteriora fecit. Duo Reges: constructio interrete. Summae mihi videtur inscitiae. Huius ego nunc auctoritatem sequens idem faciam. Quibus ego vehementer assentior.', -3),
(14, 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sint ista Graecorum; Erat enim Polemonis. Pugnant Stoici cum Peripateticis. Laboro autem non sine causa;', 0),
(15, 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. Quonam modo? Vitae autem degendae ratio maxime quidem illis placuit quieta. Duo Reges: constructio interrete.', 5), (16, 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. At hoc in eo M. Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Memini me adesse P. Si qua in iis corrigere voluit, deteriora fecit. Duo Reges: constructio interrete. Summae mihi videtur inscitiae. Huius ego nunc auctoritatem sequens idem faciam. Quibus ego vehementer assentior.', -3),
(17, 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sint ista Graecorum; Erat enim Polemonis. Pugnant Stoici cum Peripateticis. Laboro autem non sine causa;', 0),
(18, 7, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. Quonam modo? Vitae autem degendae ratio maxime quidem illis placuit quieta. Duo Reges: constructio interrete.', 5);
